export const memes = [
  {
    id: 1,
    name: "Ice Bucket Challenge",
    year: 2014,
    platform: "Facebook",
    type: "Challenge",
    category: "Social Cause",
    popularity: 95,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Ice_Bucket_Challenge.jpg",
    link: "https://www.youtube.com/results?search_query=ice+bucket+challenge",
    description: "ALS awareness campaign where people dumped ice water on themselves."
  },
  {
    id: 2,
    name: "Distracted Boyfriend",
    year: 2017,
    platform: "Instagram",
    type: "Image Meme",
    category: "Humor",
    popularity: 90,
    image: "https://upload.wikimedia.org/wikipedia/en/1/1a/Distracted_Boyfriend.jpg",
    link: "https://knowyourmeme.com/memes/distracted-boyfriend",
    description: "Stock photo turned into a viral meme about distraction."
  },
  {
    id: 3,
    name: "Harlem Shake",
    year: 2013,
    platform: "YouTube",
    type: "Trend",
    category: "Dance",
    popularity: 92,
    image: "https://upload.wikimedia.org/wikipedia/en/5/5f/Harlem_Shake_meme.jpg",
    link: "https://www.youtube.com/results?search_query=harlem+shake",
    description: "Sudden chaotic dance switch after beat drop."
  },
  {
    id: 4,
    name: "Gangnam Style",
    year: 2012,
    platform: "YouTube",
    type: "Music Meme",
    category: "Dance",
    popularity: 100,
    image: "https://upload.wikimedia.org/wikipedia/en/a/ad/Gangnam_Style_Official_Cover.png",
    link: "https://www.youtube.com/watch?v=9bZkp7q19f0",
    description: "Global viral K-pop hit by PSY."
  },
  {
    id: 5,
    name: "Woman Yelling at Cat",
    year: 2019,
    platform: "Twitter",
    type: "Image Meme",
    category: "Humor",
    popularity: 88,
    image: "https://upload.wikimedia.org/wikipedia/en/9/9a/Woman_yelling_at_cat_meme.jpg",
    link: "https://knowyourmeme.com/memes/woman-yelling-at-a-cat",
    description: "Split image meme showing argument vs confused cat."
  },
  {
    id: 6,
    name: "Damn Daniel",
    year: 2016,
    platform: "Snapchat",
    type: "Catchphrase",
    category: "Humor",
    popularity: 85,
    image: "https://upload.wikimedia.org/wikipedia/en/0/0f/Damn_Daniel.jpg",
    link: "https://www.youtube.com/results?search_query=damn+daniel",
    description: "Viral phrase praising outfits."
  },
  {
    id: 7,
    name: "Bottle Cap Challenge",
    year: 2019,
    platform: "Instagram",
    type: "Challenge",
    category: "Skill",
    popularity: 87,
    image: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Bottle_cap_challenge.jpg",
    link: "https://www.youtube.com/results?search_query=bottle+cap+challenge",
    description: "Kick bottle cap off without knocking bottle."
  },
  {
    id: 8,
    name: "Hide the Pain Harold",
    year: 2011,
    platform: "Facebook",
    type: "Image Meme",
    category: "Humor",
    popularity: 84,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Hide_the_Pain_Harold.jpg",
    link: "https://knowyourmeme.com/memes/hide-the-pain-harold",
    description: "Stock photo man with forced smile."
  },
  {
    id: 9,
    name: "Roll Safe",
    year: 2017,
    platform: "Twitter",
    type: "Image Meme",
    category: "Humor",
    popularity: 83,
    image: "https://upload.wikimedia.org/wikipedia/en/3/3f/Roll_Safe_meme.jpg",
    link: "https://knowyourmeme.com/memes/roll-safe",
    description: "Tapping head meme implying clever logic."
  },
  {
    id: 10,
    name: "Grumpy Cat",
    year: 2012,
    platform: "Reddit",
    type: "Animal Meme",
    category: "Humor",
    popularity: 91,
    image: "https://upload.wikimedia.org/wikipedia/en/5/5f/Grumpy_Cat.jpg",
    link: "https://knowyourmeme.com/memes/grumpy-cat",
    description: "Famous cat with permanently grumpy face."
  },
  {
    id: 11,
    name: "Charlie Bit My Finger",
    year: 2007,
    platform: "YouTube",
    type: "Viral Video",
    category: "Family",
    popularity: 93,
    image: "https://upload.wikimedia.org/wikipedia/en/1/1c/Charlie_bit_me.jpg",
    link: "https://www.youtube.com/watch?v=_OBlgSz8sSM",
    description: "Toddler bites brother’s finger."
  },
  {
    id: 12,
    name: "Cash Me Outside",
    year: 2016,
    platform: "TV/YouTube",
    type: "Catchphrase",
    category: "Drama",
    popularity: 86,
    image: "https://upload.wikimedia.org/wikipedia/en/4/4e/Cash_me_outside.jpg",
    link: "https://www.youtube.com/results?search_query=cash+me+outside",
    description: "Catchphrase from Dr. Phil episode."
  },
  {
    id: 13,
    name: "Is This a Pigeon?",
    year: 2018,
    platform: "Twitter",
    type: "Anime Meme",
    category: "Humor",
    popularity: 82,
    image: "https://upload.wikimedia.org/wikipedia/en/f/fd/Is_this_a_pigeon.jpg",
    link: "https://knowyourmeme.com/memes/is-this-a-pigeon",
    description: "Misidentifying objects humorously."
  },
  {
    id: 14,
    name: "Among Us Sus",
    year: 2020,
    platform: "TikTok",
    type: "Gaming Meme",
    category: "Gaming",
    popularity: 89,
    image: "https://upload.wikimedia.org/wikipedia/en/9/9a/Among_Us_cover_art.jpg",
    link: "https://www.youtube.com/results?search_query=among+us+sus",
    description: "Suspicious behavior meme from Among Us."
  },
  {
    id: 15,
    name: "OK Boomer",
    year: 2019,
    platform: "TikTok",
    type: "Phrase",
    category: "Social",
    popularity: 88,
    image: "https://upload.wikimedia.org/wikipedia/commons/9/9f/OK_Boomer.jpg",
    link: "https://www.youtube.com/results?search_query=ok+boomer",
    description: "Phrase dismissing outdated opinions."
  },
  {
    id: 16,
    name: "Coffin Dance",
    year: 2020,
    platform: "TikTok",
    type: "Music Meme",
    category: "Dark Humor",
    popularity: 94,
    image: "https://upload.wikimedia.org/wikipedia/en/3/3f/Coffin_Dance_meme.jpg",
    link: "https://www.youtube.com/results?search_query=coffin+dance",
    description: "Dancing pallbearers meme."
  },
  {
    id: 17,
    name: "Bernie Sanders Mittens",
    year: 2021,
    platform: "Twitter",
    type: "Image Meme",
    category: "Politics",
    popularity: 87,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3d/Bernie_Sanders_mittens.jpg",
    link: "https://knowyourmeme.com/memes/bernie-sanders-mittens",
    description: "Bernie sitting with mittens at inauguration."
  },
  {
    id: 18,
    name: "TikTok NPC Streaming",
    year: 2023,
    platform: "TikTok",
    type: "Trend",
    category: "Streaming",
    popularity: 80,
    image: "https://upload.wikimedia.org/wikipedia/commons/6/69/TikTok_logo.svg",
    link: "https://www.youtube.com/results?search_query=npc+stream+tiktok",
    description: "Creators acting like NPC characters on livestream."
  },
  {
    id: 19,
    name: "Skibidi Toilet",
    year: 2023,
    platform: "YouTube",
    type: "Animation Meme",
    category: "Absurd",
    popularity: 85,
    image: "https://upload.wikimedia.org/wikipedia/en/5/5c/Skibidi_Toilet.jpg",
    link: "https://www.youtube.com/results?search_query=skibidi+toilet",
    description: "Absurd animated series that went viral."
  },
  {
    id: 20,
    name: "Side Eye",
    year: 2023,
    platform: "TikTok",
    type: "Reaction Meme",
    category: "Expression",
    popularity: 83,
    image: "https://upload.wikimedia.org/wikipedia/commons/3/3a/Side_eye_expression.jpg",
    link: "https://www.youtube.com/results?search_query=side+eye+meme",
    description: "Expressing suspicion or judgment with a glance."
  }
];
